version: '3'
services:
  php-apache:
    container_name: php
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./src/html:/var/www/html/
    ports:
      - 8000:80
    links:
      - db
  db:
    container_name: db
    image: mysql:latest
    restart: always
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - 9906:3306
volumes:
  db_volume:
